# Generated by Django 5.2 on 2025-05-12 16:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_paragraph', models.TextField(blank=True, null=True, verbose_name='Intro Paragraph')),
                ('mission_statement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mission Statement')),
                ('second_paragraph', models.TextField(blank=True, null=True, verbose_name='Second Paragraph')),
                ('process_step_1', models.TextField(blank=True, null=True, verbose_name='Process Step 1')),
                ('process_step_2', models.TextField(blank=True, null=True, verbose_name='Process Step 2')),
                ('process_step_3', models.TextField(blank=True, null=True, verbose_name='Process Step 3')),
                ('process_step_4', models.TextField(blank=True, null=True, verbose_name='Process Step 4')),
                ('movement_paragraph', models.TextField(blank=True, null=True, verbose_name='Movement Paragraph')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Section Title')),
                ('content', models.TextField(blank=True, verbose_name='Section Content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to BreachXpress', max_length=200, verbose_name='Hero Title')),
                ('description', models.TextField(default='Join us in exposing corruption and empowering whistleblowers. Share your story and be part of a movement for justice.', verbose_name='Hero Description')),
                ('cta_text', models.CharField(default='Submit Your Story', max_length=100, verbose_name='CTA Text')),
                ('cta_link', models.URLField(default='#', verbose_name='CTA Link')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('section_type', models.CharField(choices=[('mission', 'Mission Section'), ('expose', 'Featured Expose Section'), ('truth', 'Why Truth Matters Section'), ('community', 'Community Section')], max_length=50, unique=True, verbose_name='Section Type')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='CTA Text')),
                ('cta_link', models.CharField(blank=True, max_length=200, verbose_name='CTA Link')),
            ],
            options={
                'verbose_name': 'Home Content Section',
                'verbose_name_plural': 'Home Content Sections',
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Link Title')),
                ('url', models.CharField(default='/', max_length=200, verbose_name='Link URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Quote Text')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='SiteMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BreachXpress', max_length=100, verbose_name='Site Name')),
                ('footer_tagline', models.CharField(default='Exposing corruption, one story at a time.', max_length=200, verbose_name='Footer Tagline')),
                ('footer_text', models.CharField(default='© 2025 BreachXpress. All Rights Reserved.', max_length=200, verbose_name='Footer Copyright Text')),
                ('contact_email', models.EmailField(default='contact@BreachXpress.com', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(default='+123-456-7890', max_length=20, verbose_name='Contact Phone')),
                ('contact_address', models.CharField(default='123, Justice Street, Truth City', max_length=200, verbose_name='Contact Address')),
                ('facebook_url', models.URLField(default='#', verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(default='#', verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(default='#', verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(default='#', verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Site Metadata',
                'verbose_name_plural': 'Site Metadata',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('story', ckeditor.fields.RichTextField(verbose_name='Story')),
                ('evidence', models.FileField(blank=True, help_text='Optional evidence file (PDF, JPG, PNG, DOC)', null=True, upload_to='evidence/', verbose_name='Evidence')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.CharField(choices=[('user_submitted', 'User Submitted'), ('investigative', 'Investigative'), ('breaking_news', 'Breaking News'), ('other', 'Other')], default='user_submitted', max_length=50, verbose_name='Category')),
                ('meta_description', models.CharField(blank=True, help_text='Custom meta description for SEO (max 160 chars)', max_length=160, verbose_name='Meta Description')),
                ('tags', models.ManyToManyField(blank=True, related_name='submitted_stories', to='Breach.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Submitted Story',
                'verbose_name_plural': 'Submitted Stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='Breach_subm_created_b9d9b5_idx'), models.Index(fields=['slug'], name='Breach_subm_slug_fad2c9_idx')],
                'unique_together': {('title', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('evidence', models.FileField(blank=True, help_text='Optional evidence file (PDF, JPG, PNG, DOC)', null=True, upload_to='evidence/', verbose_name='Evidence')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('meta_description', models.CharField(blank=True, help_text='Custom meta description for SEO (max 160 chars)', max_length=160, verbose_name='Meta Description')),
                ('tags', models.ManyToManyField(blank=True, related_name='exposes', to='Breach.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Expose',
                'verbose_name_plural': 'Exposes',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['published_date'], name='Breach_expo_publish_71ef64_idx'), models.Index(fields=['slug'], name='Breach_expo_slug_ab777c_idx')],
            },
        ),
    ]
